language: java
jdk:
#  - openjdk6
  - oraclejdk7
#  - oraclejdk8
#  - openjdk7

before_install:
  - mvn install -Pci -DskipTests=true -e

script:
  - mvn test -Pci -X

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura -P ci