/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_ginger_smarthome_hid_device_natives_Temper */

#ifndef _Included_by_ginger_smarthome_hid_device_natives_Temper
#define _Included_by_ginger_smarthome_hid_device_natives_Temper
#ifdef __cplusplus
extern "C" {
#endif
#undef by_ginger_smarthome_hid_device_natives_Temper_VENDOR_ID
#define by_ginger_smarthome_hid_device_natives_Temper_VENDOR_ID 3141L
#undef by_ginger_smarthome_hid_device_natives_Temper_PRODUCT_ID
#define by_ginger_smarthome_hid_device_natives_Temper_PRODUCT_ID 29697L
/*
 * Class:     by_ginger_smarthome_hid_device_natives_Temper
 * Method:    init
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_by_ginger_smarthome_hid_device_natives_Temper_init
  (JNIEnv *, jobject, jshort);

/*
 * Class:     by_ginger_smarthome_hid_device_natives_Temper
 * Method:    readTemperature
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_by_ginger_smarthome_hid_device_natives_Temper_readTemperature
  (JNIEnv *, jobject);

/*
 * Class:     by_ginger_smarthome_hid_device_natives_Temper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_by_ginger_smarthome_hid_device_natives_Temper_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
